function(x_display_buildin_vars)
  get_cmake_property(cmake_properties VARIABLES)
  foreach(cp ${cmake_properties})
    message( STATUS "[!!SHOW] ${cp}=${${cp}}")
  endforeach(cp ${cmake_properties})
endfunction()